import { StyleSheet } from "react-native";

const addRoundStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  inputView: {
    flexDirection: "row",
    flex: 1,
    //justifyContent: "space-between",
    width: "80%",
    marginLeft: 40,
    //marginTop: "10%",
    //alignItems: "center",
    //justifyContent: "center",
    padding: 20,
  },
  inputButtonView: {
    alignItems: "center",
  },
  textLabel: {
    flex: 1,
    fontSize: 30,
    fontWeight: "bold",
    padding: 5,
  },
  textLabelGIR: {
    fontSize: 20,
    margin: 3,
  },
  inputTextView: {
    borderColor: "green",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 5,
    width: "18%",
    height: 50,
    padding: 5,
    color: "black",
    //fontSize: 40,
    justifyContent: "center",
    //alignItems: "center",
  },
  inputTextLabels: {
    borderColor: "green",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 5,
    width: "20%",
    height: 30,
    padding: 5,
    fontSize: 5,
    alignContent: "stretch",
  },
  inputTextLgn: {
    flex: 1,
    height: 50,
    width: "100%",
    borderColor: "black",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "stretch",
    justifyContent: "center",
    alignContent: "stretch",
  },
  loginBtn: {
    width: "80%",
    backgroundColor: "#009933",
    borderRadius: 10,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 30,

    shadowColor: "rgba(46, 45, 49, 0.8)",
    shadowOpacity: 1.5,
    elevation: 8,
    shadowRadius: 20,
    shadowOffset: { width: 1, height: 15 },
  },
  loginBtnTxt: {
    fontSize: 21,
    color: "white",
  },
  //   columnView: {
  //     flex: 1,
  //     flexDirection: "column",
  //     marginTop: 30,
  //   },
  imageView: {
    alignItems: "center",
  },
  pickerStyle: {
    fontSize: 10,
    color: "black",
    paddingRight: 60,
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    paddingRight: 5,
  },
  optionalLabel: {
    flex: 1,
    fontSize: 10,
  },
  inputTextViewNotes: {
    borderColor: "green",
    borderStyle: "solid",
    borderWidth: 2,
    borderRadius: 5,
    width: "45%",
    height: 30,
    padding: 5,
    color: "black",
    alignItems: "stretch",
    justifyContent: "center",
  },
  scoreText: {
    flex: 1,
    height: 50,
    width: "100%",
    borderColor: "black",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 10,
    fontSize: 42,
    color: "red",
    //alignItems: "stretch",
    //justifyContent: "center",
    //alignContent: "stretch",
  },
});

export default addRoundStyles;
