$FirebaseSDKVersion = '7.7.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'Firebase'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'gbapp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end
